import { useState, useEffect, useCallback } from 'react';
import { agentApi } from '../../services/api/agent';
import LoadingSpinner from '../common/LoadingSpinner.jsx';
import ApprovalPanel from './ApprovalPanel.jsx';

export default function AgentDashboard() {
  const [reports, setReports] = useState([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);

  const fetchPending = useCallback(async () => {
    setLoading(true);
    try {
      const { reports: pending } = await agentApi.listPending();
      setReports(pending);
      setError(null);
    } catch (err) {
      setError(err.response?.data?.error || err.message);
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => {
    fetchPending();
    // Poll every 10s so newly-processed reports show up without a manual refresh
    const handle = setInterval(fetchPending, 10000);
    return () => clearInterval(handle);
  }, [fetchPending]);

  function handleResolved(reportId) {
    setReports((prev) => prev.filter((r) => r._id !== reportId));
  }

  if (loading && reports.length === 0) return <LoadingSpinner label="Loading pending reviews..." />;
  if (error) return <p className="text-sm text-status-critical">{error}</p>;

  return (
    <div>
      <h1 className="text-xl font-bold text-text-primary">Agent Review Queue</h1>
      <p className="mt-1 text-sm text-text-muted">
        Draft plans generated by the agent are listed here, sorted by urgency, until a responder
        approves or rejects them. Nothing here has been acted on yet.
      </p>

      {reports.length === 0 ? (
        <p className="mt-8 text-center text-sm text-text-muted">
          No reports are currently awaiting review. 🎉
        </p>
      ) : (
        <div className="mt-6 grid grid-cols-1 gap-4 lg:grid-cols-2">
          {reports.map((r) => (
            <ApprovalPanel key={r._id} report={r} onResolved={handleResolved} />
          ))}
        </div>
      )}
    </div>
  );
}
